# Generated by Django 6.1 on 2026-08-31 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('payment_status', models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending'), ('Terminated', 'Terminated')], max_length=20)),
                ('payment_method', models.CharField(choices=[('Card', 'Card'), ('Cash', 'Cash')], max_length=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=20)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('receipt_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('receipt_number', models.CharField(max_length=20, unique=True)),
                ('issued_date', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.payment')),
            ],
        ),
    ]
