# Generated by Django 5.2.9 on 2026-09-01 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='has_nin',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nin',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
