# Generated by Django 5.2.9 on 2026-09-01 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
    ]
