# Generated by Django 6.1 on 2026-09-01 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='cost',
            new_name='unit_cost',
        ),
    ]
