# Generated by Django 5.2.9 on 2026-09-01 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_job_role_employee_user'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partsrequest',
            name='issued_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts_issued', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='partsrequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parts_requested', to='employees.employee'),
        ),
    ]
