# Generated by Django 6.1 on 2026-08-31 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=15)),
                ('customer_email', models.EmailField(max_length=30, unique=True)),
                ('phone_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('size', models.CharField(choices=[('Heavy', 'Heavy'), ('Commercial', 'Commercial'), ('Small', 'Small')], max_length=20)),
                ('car_model', models.CharField(blank=True, max_length=50)),
                ('number_plate', models.CharField(max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField(blank=True)),
                ('role', models.ManyToManyField(to='employees.role')),
                ('service', models.ManyToManyField(to='services.service')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('inpection_id', models.AutoField(primary_key=True, serialize=False)),
                ('findings', models.CharField(max_length=100)),
                ('recommended_service', models.CharField(max_length=50)),
                ('done_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.vehicle')),
            ],
        ),
    ]
