# Generated by Django 6.1 on 2026-09-01 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inspection',
            old_name='inpection_id',
            new_name='inspection_id',
        ),
    ]
